config/routes.rb
LoLFantasy::Application.routes.draw do
  
  get "team/:id/sell/:player" => 'teams#sell', as: 'sell_player'
  get "team/:id/buy/:player" => 'teams#buy', as: 'buy_player'
  get "manage/:id" => 'teams#manage', as: 'manage_team'
  
  get "join/:league/" => 'teams#new', as: 'new_team'
  get "join/:league/:token" => 'teams#new', as: 'new_team_token'
  post "join/:league/" => 'teams#create', as: 'create_team'

  get "rankings" => "teams#rankings", as: 'rankings'  
  get "leagues/:id/rankings" => "leagues#rankings", as: 'league_rankings'
  
  resources :players
  resources :leagues
  resources :teams

  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}

  root "home#index"

end

app/models/league.rb
class League < ActiveRecord::Base
	belongs_to :user
	has_many :teams, dependent: :destroy
	validates :name, uniqueness: true, length: {maximum: 30, minimum:4}
	before_create :generate_token

	def generate_token
		self.token = ('a'..'z').to_a.shuffle[0,8].join
	end

	def to_param
		"#{id}-#{name}".parameterize
	end
end

app/controllers/leagues_controller.rb
class LeaguesController < ApplicationController
  before_action :set_league, only: [:show, :edit, :update, :destroy, :rankings]
  before_filter :authenticate_user!, except: [:index, :show, :rankings]
  before_filter :modify_league?, only: [:edit, :update, :destroy]
  # GET /leagues
  # GET /leagues.json
  def index
    @leagues = League.where(private: false)
  end

  # GET /leagues/1
  # GET /leagues/1.json
  def show
  end

  def rankings
    @teams = @league.teams.order("points DESC, budget DESC")
  end

  # GET /leagues/new
  def new
    @league = League.new
  end

  # GET /leagues/1/edit
  def edit
  end

  # POST /leagues
  # POST /leagues.json
  def create
    @league = current_user.leagues.new(league_params)

    respond_to do |format|
      if @league.save
        format.html { redirect_to @league, notice: 'League was successfully created.' }
        format.json { render action: 'show', status: :created, location: @league }
      else
        format.html { render action: 'new' }
        format.json { render json: @league.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /leagues/1
  # PATCH/PUT /leagues/1.json
  def update
    respond_to do |format|
      if @league.update(league_params)
        format.html { redirect_to @league, notice: 'League was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @league.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /leagues/1
  # DELETE /leagues/1.json
  def destroy
    @league.destroy
    respond_to do |format|
      format.html { redirect_to leagues_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_league
      @league = League.find(params[:id])
    end

    def modify_league?
      unless current_user == @league.user
        redirect_to root_path, error: "Only the creator of the league may edit it."
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def league_params
      params.require(:league).permit(:name, :user_id, :private, :start_week)
    end
end

app/helpers/leagues_helper.rb
module LeaguesHelper
end

app/views/leagues/_form.html.erb
<%= simple_form_for(@league) do |f| %>
<% if @league.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@league.errors.count, "error") %> prohibited this league from being saved:</h2>

  <ul>
    <% @league.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="field">
  <%= f.input :name, required: true %>
</div>
<div class="field">
  <%= f.input :start_week, required: true %>
</div>
<div class="field">
  <%= f.input :private %>
</div>
<div class="actions">
  <%= f.submit class: 'btn btn-primary' %>
</div>
<% end %>

app/views/leagues/edit.html.erb
<h1>Editing league</h1>

<%= render 'form' %>

<%= link_to 'Show', @league %> |
<%= link_to 'Back', leagues_path %>

app/views/leagues/index.html.erb
<h1>Listing leagues</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Creator</th>
      <th>Start week</th>
      <th>Join</th>
      <th>Rankings</th>
    </tr>
  </thead>

  <tbody>
    <% @leagues.each do |league| %>
      <tr>
        <td><%= link_to league.name, league %></td>
        <td><%= league.user.username %></td>
        <td><%= league.start_week %></td>
        <td>
          <% if (league.private) %>
          Private
        <% else %>
          <%= link_to "Join", new_team_path(league), class: 'btn btn-primary' %>
        <% end %>
        </td>
        <td><%= link_to "Rankings", league_rankings_path(league), class: 'btn btn-info' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New League', new_league_path %>

app/views/leagues/new.html.erb
<h1>New league</h1>

<%= render 'form' %>

<%= link_to 'Back', leagues_path %>

app/views/leagues/rankings.html.erb
<h1>Ranking for <%= @league.name %></h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Team</th>
      <th>Points</th>
      <th>Budget</th>
    </tr>
  </thead>

  <tbody>
    <% @teams.each do |team| %>
      <tr>
        <td><%= link_to team.name, team %></td>
        <td><%= team.points %></td>
        <td><%= team.budget %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/leagues/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @league.name %>
</p>

<p>
  <strong>Creator:</strong>
  <%= @league.user.username %>
</p>

<p>
  <strong>Private:</strong>
  <%= @league.private ? "Yes" : "No" %>
</p>

<p>
  <strong>Start week:</strong>
  <%= @league.start_week %>
</p>

<% if current_user == @league.user && @league.private %>
	<p>
		<strong><%= link_to "Join League Link (Users can't join without this link)", new_team_token_path(@league, @league.token) %></strong>
	<p>
	<%= link_to 'Edit', edit_league_path(@league) %> |
<% end %>
<%= link_to 'Join', @league.private ? new_team_token_path(@league, @league.token) : new_team_path(@league) %> |
<%= link_to 'Rankings', league_rankings_path(@league) %> |
<%= link_to 'Back', leagues_path %>