config/routes.rb
LoLFantasy::Application.routes.draw do
  
  get "team/:id/sell/:player" => 'teams#sell', as: 'sell_player'
  get "team/:id/buy/:player" => 'teams#buy', as: 'buy_player'
  get "manage/:id" => 'teams#manage', as: 'manage_team'
  
  get "join/:league/" => 'teams#new', as: 'new_team'
  get "join/:league/:token" => 'teams#new', as: 'new_team_token'
  post "join/:league/" => 'teams#create', as: 'create_team'

  get "rankings" => "teams#rankings", as: 'rankings'  
  get "leagues/:id/rankings" => "leagues#rankings", as: 'league_rankings'
  
  resources :players
  resources :leagues
  resources :teams

  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}

  root "home#index"

end

app/models/player.rb
class Player < ActiveRecord::Base
	has_many :stats, class_name: 'Stats'
	belongs_to :team_player

	def to_param
		name
	end

	def total_points
		t = 0
		stats.each do |stat|
			t = t + stat.points
		end
		return t
	end

	def kda
		kills = 0
		deaths = 0
		assists = 0
		stats.each do |stat|
			kills += stat.kills
			deaths += stat.deaths
			assists += stat.assists
		end
		return (kills + deaths) / assists.to_f
	end

	def csmin
		cs = 0
		mins = 0
		stats.each do |stat|
			cs += stat.cs
			mins += stat.game_mins
		end
		return cs/mins
	end

	def sell_price
		price * 0.75
	end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: [:show, :edit, :update, :destroy]

  # GET /players
  # GET /players.json
  def index
    @players = Player.all
  end

  # GET /players/1
  # GET /players/1.json
  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player
      @player = Player.find_by_name(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def player_params
      params.require(:player).permit(:name, :price, :position)
    end
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/players/_form.html.erb
<%= form_for(@player) do |f| %>
  <% if @player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
      <% @player.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :position %><br>
    <%= f.text_field :position %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/players/edit.html.erb
<h1>Editing player</h1>

<%= render 'form' %>

<%= link_to 'Show', @player %> |
<%= link_to 'Back', players_path %>

app/views/players/index.html.erb
<h1>Listing players</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Position</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @players.each do |player| %>
      <tr>
        <td><%= player.name %></td>
        <td><%= player.price %></td>
        <td><%= player.role %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/players/new.html.erb
<h1>New player</h1>

<%= render 'form' %>

<%= link_to 'Back', players_path %>

app/views/players/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @player.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @player.price %>
</p>

<p>
  <strong>Role:</strong>
  <%= @player.role %>
</p>

<p>
  <strong>KDA:</strong>
  <%= @player.kda %>
</p>
<p>
	<strong>CS/min:</strong>
	<%= @player.csmin %>
</p>
<p>
	<strong><a href="#" data-rel="popover" data-toggle="popover" data-content="Supports : KDA * 2.<br>Everyone else: KDA + cs/min" data-title="Point Calculation" data-html="true" data-no-turbolink>Points:</a></strong>
	<%= @player.total_points %>
</p>
<%= link_to 'Back', players_path %>