config/routes.rb
LoLFantasy::Application.routes.draw do
  
  get "team/:id/sell/:player" => 'teams#sell', as: 'sell_player'
  get "team/:id/buy/:player" => 'teams#buy', as: 'buy_player'
  get "manage/:id" => 'teams#manage', as: 'manage_team'
  
  get "join/:league/" => 'teams#new', as: 'new_team'
  get "join/:league/:token" => 'teams#new', as: 'new_team_token'
  post "join/:league/" => 'teams#create', as: 'create_team'

  get "rankings" => "teams#rankings", as: 'rankings'  
  get "leagues/:id/rankings" => "leagues#rankings", as: 'league_rankings'
  
  resources :players
  resources :leagues
  resources :teams

  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}

  root "home#index"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<title>LoLFantasy</title>
	<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
	<script type="text/javascript" src="https://www.google.com/jsapi"></script>
	<%= javascript_include_tag "application" %>
	<%= csrf_meta_tags %>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="author" content="Anujan Panchadcharam (MrQuackers / @anujanpan)">
	<link href='http://fonts.googleapis.com/css?family=Lato:400,700,300' rel='stylesheet' type='text/css'>
<!--[if IE]>
	<link href="http://fonts.googleapis.com/css?family=Lato" rel="stylesheet" type="text/css">
	<link href="http://fonts.googleapis.com/css?family=Lato:400" rel="stylesheet" type="text/css">
	<link href="http://fonts.googleapis.com/css?family=Lato:700" rel="stylesheet" type="text/css">
	<link href="http://fonts.googleapis.com/css?family=Lato:300" rel="stylesheet" type="text/css">
	<![endif]-->
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<!--[if IE 7]>
<link rel="stylesheet" href="css/font-awesome-ie7.min.css">
<![endif]-->
</head>
<body>
	<div class="header ">
		<div class="container">
			<div class="logo">
				<a href="<%= url_for root_path %>"><%= image_tag "logo.png" %></a>
			</div>
			<nav id="main_menu">
				<div class="menu_wrap">
					<ul class="nav sf-menu">
						<%= nav_link "Home", root_path %>
						<%= nav_link "Leagues", leagues_path %>
						<% if user_signed_in? %>
						<%= nav_link "My Teams", teams_path	%>
						<%= nav_link "Sign out", destroy_user_session_path, method: :delete %>
						<% else %>
						<%= nav_link "Sign in", new_user_session_path %>
						<%= nav_link "Sign up", new_user_registration_path %>
						<% end %>
					</ul>
				</div>
			</nav>
		</div>
	</div>
	<div class="container wrapper">
		<div class="ads">
			<script type="text/javascript"><!--
google_ad_client = "ca-pub-8742083424682828";
/* FantasyLoL */
google_ad_slot = "8690024786";
google_ad_width = 728;
google_ad_height = 90;
//-->
</script>
<script type="text/javascript"
src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
</script>
		</div>
		<div class="inner_content">
			<%= bootstrap_flash %>
			<%= yield %>
		</div>
	</div>
	<div id="footer2">
		<div class="container">
			<div class="row">
				<div class="span12">
					<div class="copyright">
						LoLFantasy
						&copy; 2013
						- All Rights Reserved
					</div>
					<div class="copyright">
						Powered by <a href="http://shurima.net">Shurima.NET</a>
					</div>
				</div>
			</div>
		</div>
	</div>
	<a href="#"><i class="go-top hidden-phone hidden-tablet  icon-double-angle-up"></i></a>
	<script type="text/javascript">
	var _gaq = _gaq || [];
	_gaq.push(['_setAccount', 'UA-34465335-1']);
	_gaq.push(['_trackPageview']);
	(function() {
		var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
		ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
		var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
	})();
	</script>
</body>
</html>	